print(" === Best Recepy in the World! === ")
type = input("What type of food do you prefer?: ")
plant = input("What type of plant do you like?: ")
method = input("Choose method of cooking: ")
special = input("Add special topping: ")
pot = input("Peek a tableware: ")
print()
print("MENU")
print(method, type, "with", special, plant, "in", pot)
