yourName = input("What's your name?")
print("Thank you")
print(yourName)
yourFood = input("What's your favorite food?: ") 
print("Your favorite food is")
print(yourFood)
yourMusic = input("What's your favorite music?: ")
print("Your favorite music is")
print(yourMusic)
yourLocation = input ("What's your location?: ")
print("Your location is")
print(yourLocation)